name: localhost
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${name}:${server.port}/eureka/

spring:
  application:
    name: eureka-server